---
title: "Overview"
author: "Elise Hellwig"
---


## Description

The R programming language has a vast and sprawling documentation library, and
a lot of it is in a standardized format: the R help file. Unfortunately, R help 
files can be difficult to read at the best of times, and almost impossible to
understand for those new to coding. This workshop will explain each section 
of the R help file, how to read them, and when they are the most useful. It 
will also introduce you a number of ways to search R documentation, both from R
and on the internet.


**Workshop site:** [https://d-rug.github.io/help_file_anatomy/][anatomy]

[anatomy]: https://d-rug.github.io/help_file_anatomy/

## Learning Objectives 

  * Know where to look for R documentation depending on what type of question 
  you need answered
  
  * Understand what information each section of an R help file contains 
  
  * Be able to use a help file to determine the following things about a
  function 
    * What arguments are required?
    * What the class of those arguments needs to be?
    * What are the default values for various arguments?
    * What are the function's outputs?
  
## Setup

```{r message=FALSE}

if (!require('sf')) install.packages('sf')
if (!require('forcats')) install.packages('forcats')


```

